'use client';
import { FormEvent, useEffect, useState } from 'react';

type Link = { id: number; name: string; url: string; group_name: string };
type Group = { name: string };
type View = 'menu' | 'add' | 'list' | 'settings';
const request = (url: string, options?: RequestInit) => fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) } });

export default function Home() {
  const [ready, setReady] = useState(false), [loggedIn, setLoggedIn] = useState(false), [theme, setTheme] = useState('white'), [view, setView] = useState<View>('menu'), [error, setError] = useState(''), [links, setLinks] = useState<Link[]>([]), [groups, setGroups] = useState<Group[]>([]), [groupsCollapsed, setGroupsCollapsed] = useState(false);
  useEffect(() => { request('/api/auth').then(r => r.json()).then(d => { setLoggedIn(d.authenticated); setTheme(d.theme || 'white'); setGroupsCollapsed(Boolean(d.groupsCollapsed)); setReady(true); }); }, []);
  const loadLinks = async () => { const r = await request('/api/links'); if (r.ok) { const data = await r.json(); setLinks(data.links); setGroups(data.groups); setGroupsCollapsed(Boolean(data.groupsCollapsed)); } };
  useEffect(() => { if (loggedIn && view === 'list') loadLinks(); }, [loggedIn, view]);
  if (!ready) return null;
  if (!loggedIn) return <main className={`page ${theme}`}><section className="card login"><h1>Links</h1><form onSubmit={async e => { e.preventDefault(); const p = new FormData(e.currentTarget).get('password'); const r = await request('/api/auth', { method: 'POST', body: JSON.stringify({ password: p }) }); if (r.ok) { setLoggedIn(true); setError(''); } else setError('Wrong password'); }}><label>Enter password<input autoFocus name="password" type="password" required /></label><button>Enter</button>{error && <p className="error">{error}</p>}</form></section></main>;
  const nav = (next: View) => <button className="menu-button" onClick={() => setView(next)}>{next === 'add' ? 'Add links' : next === 'list' ? 'List links' : 'Settings'}</button>;
  return <main className={`page ${theme}`}><section className="card"><header><h1>Links</h1>{view !== 'menu' && <button className="plain" onClick={() => setView('menu')}>← Menu</button>}</header>{view === 'menu' && <div className="menu">{nav('add')}{nav('list')}{nav('settings')}<button className="plain logout" onClick={async () => { await request('/api/auth', { method: 'DELETE' }); setLoggedIn(false); }}>Log out</button></div>}{view === 'add' && <Add onDone={() => setView('menu')} />}{view === 'list' && <List links={links} groups={groups} groupsCollapsed={groupsCollapsed} reload={loadLinks} />}{view === 'settings' && <Settings theme={theme} setTheme={setTheme} groupsCollapsed={groupsCollapsed} setGroupsCollapsed={setGroupsCollapsed} />}</section></main>;
}
function Add({ onDone }: { onDone: () => void }) { const [error, setError] = useState(''); return <form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await request('/api/links', { method: 'POST', body: JSON.stringify({ name: f.get('name'), url: f.get('url'), group: f.get('group') }) }); if (r.ok) onDone(); else setError((await r.json()).error); }}><label>Name<input name="name" required /></label><label>Link<input name="url" type="text" placeholder="example.com" required /></label><label>Group<input name="group" /></label><button>Add link</button>{error && <p className="error">{error}</p>}</form>; }
function List({ links, groups, groupsCollapsed, reload }: { links: Link[]; groups: Group[]; groupsCollapsed: boolean; reload: () => Promise<void> }) { const [collapsed, setCollapsed] = useState<Record<string, boolean>>({}); const [newGroup, setNewGroup] = useState(''); const [error, setError] = useState(''); const names = Array.from(new Set([...groups.map(g => g.name), ...links.map(l => l.group_name).filter(Boolean)])); if (links.some(l => !l.group_name)) names.unshift(''); const addGroup = async (e: FormEvent) => { e.preventDefault(); const r = await request('/api/groups', { method: 'POST', body: JSON.stringify({ name: newGroup }) }); if (r.ok) { setNewGroup(''); setError(''); reload(); } else setError((await r.json()).error); }; return <div><form className="group-form" onSubmit={addGroup}><label>Create group<input value={newGroup} onChange={e => setNewGroup(e.target.value)} placeholder="Group name" required /></label><button>Create group</button>{error && <p className="error">{error}</p>}</form>{!names.length ? <p className="muted">No links or groups yet.</p> : names.map(name => { const groupLinks = links.filter(l => l.group_name === name); const isCollapsed = collapsed[name] ?? groupsCollapsed; return <section className="group" key={name || '__ungrouped'}><button className="group-title" onClick={() => setCollapsed(s => ({ ...s, [name]: !isCollapsed }))}><span>{name || 'Without group'} <small>({groupLinks.length})</small></span><span>{isCollapsed ? '+' : '−'}</span></button>{!isCollapsed && <div>{!groupLinks.length && <p className="muted">No links in this group.</p>}{groupLinks.map(l => <article className="link" key={l.id}><a href={l.url} target="_blank" rel="noreferrer">{l.name}</a><button className="delete" aria-label={`Delete ${l.name}`} onClick={async () => { await request('/api/links', { method: 'DELETE', body: JSON.stringify({ id: l.id }) }); reload(); }}>−</button></article>)}</div>}</section>; })}</div>; }
function Settings({ theme, setTheme, groupsCollapsed, setGroupsCollapsed }: { theme: string; setTheme: (s: string) => void; groupsCollapsed: boolean; setGroupsCollapsed: (value: boolean) => void }) { const [message, setMessage] = useState(''); const saveTheme = async (value: string) => { const r = await request('/api/settings', { method: 'PATCH', body: JSON.stringify({ theme: value }) }); if (r.ok) setTheme(value); }; const saveGroupsDefault = async (value: boolean) => { const r = await request('/api/settings', { method: 'PATCH', body: JSON.stringify({ groupsCollapsed: value }) }); if (r.ok) setGroupsCollapsed(value); }; return <><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await request('/api/settings', { method: 'PATCH', body: JSON.stringify({ password: f.get('password'), confirmPassword: f.get('confirm') }) }); setMessage(r.ok ? 'Password changed.' : (await r.json()).error); if (r.ok) e.currentTarget.reset(); }}><label>Change password<input name="password" type="password" minLength={4} required /></label><label>Confirm change password<input name="confirm" type="password" minLength={4} required /></label><button>Save password</button>{message && <p className={message === 'Password changed.' ? 'success' : 'error'}>{message}</p>}</form><div className="theme"><span>Style:</span><button className={theme === 'white' ? 'selected' : ''} onClick={() => saveTheme('white')}>White</button><button className={theme === 'black' ? 'selected' : ''} onClick={() => saveTheme('black')}>Black</button></div><div className="theme"><span>Groups open by default:</span><button className={!groupsCollapsed ? 'selected' : ''} onClick={() => saveGroupsDefault(false)}>Yes</button><button className={groupsCollapsed ? 'selected' : ''} onClick={() => saveGroupsDefault(true)}>No</button></div></>; }
