'use client';
import { FormEvent, useEffect, useState } from 'react';

type Link = { id: number; name: string; url: string; group_name: string };
type View = 'menu' | 'add' | 'list' | 'settings';
const request = (url: string, options?: RequestInit) => fetch(url, { ...options, headers: { 'Content-Type': 'application/json', ...(options?.headers || {}) } });

export default function Home() {
  const [ready, setReady] = useState(false), [loggedIn, setLoggedIn] = useState(false), [theme, setTheme] = useState('white'), [view, setView] = useState<View>('menu'), [error, setError] = useState(''), [links, setLinks] = useState<Link[]>([]);
  useEffect(() => { request('/api/auth').then(r => r.json()).then(d => { setLoggedIn(d.authenticated); setTheme(d.theme || 'white'); setReady(true); }); }, []);
  const loadLinks = async () => { const r = await request('/api/links'); if (r.ok) setLinks(await r.json()); };
  useEffect(() => { if (loggedIn && view === 'list') loadLinks(); }, [loggedIn, view]);
  if (!ready) return null;
  if (!loggedIn) return <main className={`page ${theme}`}><section className="card login"><h1>Links</h1><form onSubmit={async e => { e.preventDefault(); const p = new FormData(e.currentTarget).get('password'); const r = await request('/api/auth', { method: 'POST', body: JSON.stringify({ password: p }) }); if (r.ok) { setLoggedIn(true); setError(''); } else setError('Wrong password'); }}><label>Enter password<input autoFocus name="password" type="password" required /></label><button>Enter</button>{error && <p className="error">{error}</p>}</form></section></main>;
  const nav = (next: View) => <button className="menu-button" onClick={() => setView(next)}>{next === 'add' ? 'Add links' : next === 'list' ? 'List links' : 'Settings'}</button>;
  return <main className={`page ${theme}`}><section className="card"><header><h1>Links</h1>{view !== 'menu' && <button className="plain" onClick={() => setView('menu')}>← Menu</button>}</header>{view === 'menu' && <div className="menu">{nav('add')}{nav('list')}{nav('settings')}<button className="plain logout" onClick={async () => { await request('/api/auth', { method: 'DELETE' }); setLoggedIn(false); }}>Log out</button></div>}{view === 'add' && <Add onDone={() => setView('menu')} />}{view === 'list' && <List links={links} reload={loadLinks} />}{view === 'settings' && <Settings theme={theme} setTheme={setTheme} />}</section></main>;
}
function Add({ onDone }: { onDone: () => void }) { const [error, setError] = useState(''); return <form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await request('/api/links', { method: 'POST', body: JSON.stringify({ name: f.get('name'), url: f.get('url'), group: f.get('group') }) }); if (r.ok) onDone(); else setError((await r.json()).error); }}><label>Name<input name="name" required /></label><label>Link<input name="url" type="text" placeholder="example.com" required /></label><label>Group<input name="group" /></label><button>Add link</button>{error && <p className="error">{error}</p>}</form>; }
function List({ links, reload }: { links: Link[]; reload: () => Promise<void> }) { return <div>{!links.length ? <p className="muted">No links yet.</p> : links.map(l => <article className="link" key={l.id}><div>{l.group_name && <small>{l.group_name}</small>}<a href={l.url} target="_blank" rel="noreferrer">{l.name}</a></div><button className="delete" aria-label={`Delete ${l.name}`} onClick={async () => { await request('/api/links', { method: 'DELETE', body: JSON.stringify({ id: l.id }) }); reload(); }}>−</button></article>)}</div>; }
function Settings({ theme, setTheme }: { theme: string; setTheme: (s: string) => void }) { const [message, setMessage] = useState(''); const saveTheme = async (value: string) => { const r = await request('/api/settings', { method: 'PATCH', body: JSON.stringify({ theme: value }) }); if (r.ok) setTheme(value); }; return <><form onSubmit={async e => { e.preventDefault(); const f = new FormData(e.currentTarget); const r = await request('/api/settings', { method: 'PATCH', body: JSON.stringify({ password: f.get('password'), confirmPassword: f.get('confirm') }) }); setMessage(r.ok ? 'Password changed.' : (await r.json()).error); if (r.ok) e.currentTarget.reset(); }}><label>Change password<input name="password" type="password" minLength={4} required /></label><label>Confirm change password<input name="confirm" type="password" minLength={4} required /></label><button>Save password</button>{message && <p className={message === 'Password changed.' ? 'success' : 'error'}>{message}</p>}</form><div className="theme"><span>Style:</span><button className={theme === 'white' ? 'selected' : ''} onClick={() => saveTheme('white')}>White</button><button className={theme === 'black' ? 'selected' : ''} onClick={() => saveTheme('black')}>Black</button></div></>; }
